### ISSUE TITLE
Question about geli encrypted boot drive

### ISSUE THREAD

**Issue by agregson** [vermaden/beadm#27]
Hello,

I tried to migrate to beadm type structure on 10.0 and am not successful. Before I try it again, I wanted to check and be clear if sysutils/beadm or sysutil/devel-beadm can boot from a geli encrypted drive? 

The startup drive is configured as follows:
gpart show ada0
=>        34  1000215149  ada0  GPT  (477G)
          34        1024     1  freebsd-boot  (512K)
        1058         990        - free -  (495K)
        2048    83886080     2  freebsd-swap  (40G)
    83888128   916327055     3  freebsd-zfs  (437G)

The third partition is encrypted and requires a password at boot. Essentially, I could never get beadm to recognize the boot environment on that partition. 

Thanks,

**Comment by vermaden** [comment]
Its not about beadm, the FreeBSD itself it not able too boot from ZFS on top of GELI, but this can change as its one of the projects for the year's GSoC.

Regards,
vermaden

**Comment by agregson** [comment]
This is not true. I have been booting a ZFS on top of GELI boot drive since before I posted the above comment. Perhaps there are problems with it though I haven't experienced any yet.
