### ISSUE TITLE
BE name ending with colon not bootable on FreeBSD.

### ISSUE THREAD

**Issue by maurizio-emmex** [vermaden/beadm#30]
If I create and activate a BE ending with a colon eg. 'TEST:' the environment is not bootable:
the FreeBSD loader gives an error message:
can't load 'kernel'

I am running FreeBSD 11.0-CURRENT.

Regards,
Maurizio

**Comment by vermaden** [comment]
Fixed (added name sanity check upon creation): 
https://github.com/vermaden/beadm/commit/7c1b1de2a6af28ae3c8dc230a715a3096ecb64ad

Regards,
vermaden

**Comment by maurizio-emmex** [comment]
2015-09-08 9:48 GMT+02:00 vermaden <notifications@github.com>:

> Fixed (added name sanity check upon creation):
> 7c1b1de
> <https://github.com/vermaden/beadm/commit/7c1b1de2a6af28ae3c8dc230a715a3096ecb64ad>
>
> Regards,
> vermaden
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vermaden/beadm/issues/30#issuecomment-138465119>.
>
Thank you for the fix and for your work.

Regards,
Maurizio

**Comment by vermaden** [comment]
Welcome ;)
