### ISSUE TITLE
Preparing filesystem to benefit from beadm with 10.2

### ISSUE THREAD

**Issue by priyadarshan** [vermaden/beadm#31]
Hi,

I was reading the how-to, and I noticed it was written in April 2012:

https://cdn.rawgit.com/vermaden/beadm/master/HOWTO.htm

I was wondering if anything has changed in regards of preparing filesystem to benefit from beadm while installing FreeBSD 10.2?

**Comment by vermaden** [comment]
I should still work the same, if not, please create new issue about it ;)

Regards,
vermaden
