### ISSUE TITLE
Create /boot/entropy when activating new BE

### ISSUE THREAD

**Issue by lattera** [vermaden/beadm#32]
When activating a new BE and rebooting into it, the /boot/entropy file will be from the previous boot. As such, there would be deterministic seeding of the entropy pool. You can create a new /boot/entropy by doing `dd if=/dev/random of=/path/to/mounted/be/boot/entropy bs=4096 count=1`.

**Comment by vermaden** [comment]
On my system I do not have the /boot/entropy file:
# ls -l /boot/entropy
# uname -v
FreeBSD 10.2-STABLE #0: Sat Aug 22 14:11:03 CEST 2015     root@w530.local:/usr/obj/usr/src/sys/GENERIC 

Should I just create it with that dd(1) command?

Regards,
vermaden

**Comment by lattera** [comment]
Yeah, that file really needs to be created and the dd command will work, adjusting for the output file path, of course. `/boot/entropy` exists on my system:

        hbsd-dev-laptop[shawn]:/home/shawn $ ls -l /boot/entropy
        -rw-------  1 root  wheel  4096 Sep 12 08:54 /boot/entropy
        hbsd-dev-laptop[shawn]:/home/shawn $ uname -a
        FreeBSD hbsd-dev-laptop 11.0-CURRENT-HBSD FreeBSD 11.0-CURRENT-HBSD #1 6bc41a8(hardened/current/master)-dirty: Fri Sep 11 10:33:21 EDT 2015     shawn@hbsd-dev-laptop:/usr/obj/usr/src/sys/LATT-SEC  amd64

**Comment by vermaden** [comment]
Added in slighty different way, secure current /boot/entropy, create new one, create snapshot for BE, bring back original /boot/entropy file, here:

  # secure current /boot/entropy file
  if [ -f /boot/entropy ]
  then
    cp -p /boot/entropy /boot/entropy.OLD
  fi
  # create new /boot/entropy file that would be used in new boot environment
  if ! dd if=/dev/random of=/boot/entropy bs=4096 count=1 1> /dev/null 2> /dev/null
  then
    echo "ERROR: Can not generate new '/boot/entropy' file"
    exit 1
  fi

< NEW BE CREATION FROM SNAPSHOT >

  # bring back secured /boot/entropy.OLD file
  if [ -f /boot/entropy.OLD ]
  then
    mv /boot/entropy.OLD /boot/entropy
  fi



Regards,
vermaden

**Comment by lattera** [comment]
That works for me. Thanks a lot!

**Comment by vermaden** [comment]
Even more checks for safety ...

https://github.com/vermaden/beadm/commit/f5a02cdbc07a9d7511e123d22d121b218c206b93

**Comment by vermaden** [comment]
BEADM 1.2.6 added as update request to my previous request:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=202965

**Comment by bdrewery** [comment]
This was lost, PR #50 restores it.
