### ISSUE TITLE
Create new / set active BEs to canmount=noauto to ease backups.

### ISSUE THREAD

**Issue by eborisch** [vermaden/beadm#36]
### Short version
Use _canmount=noauto_ for all (even active) BEs; the boot loader uses _bootfs_ and mount it anyway and off we go. This makes backups less error-prone.

### Long version
The FreeBSD boot loader (tested on 10.3) will happily boot into and mount a _canmount=noauto_ filesystem pointed to by the zpool's _bootfs_ property. (By the by, it will happily mount a _canmount=off_ filesystem pointed to by _bootfs_, too.) By setting all BEs to _noauto_ -- rather than having the active one set to _on_ in addition to being pointed to by _bootfs_ -- a ZFS send/recv of the root pool or filesystems (BEs) to another location won't have the possibility of mounting over the root partition. (See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=210222)

Is there any drawback to setting _canmount=noauto_ here? The only one I can think of is if this pool is imported from another (e.g. livecd) system with _altroot_; the resulting fs won't come up quite how you would "hope"; but I would suggest this is a recovery situation and is OK; performing a zfs send/recv to perform a backup of your system and being rewarded with havoc on reboot is much more disruptive.

This won't address any other mount points (/usr/home, or /var/log, etc.) that may be getting backed up from also needing special care, but those filesystems are much less likely to be appear after initial backups (unlike new BEs; especially if created with -e), and also are less disruptive (you have a good chance of umount-ing them) than stacking onto /.

**Comment by allanjude** [comment]
This is required for them to work via the beastie menu as well

**Comment by allanjude** [comment]
This is already pending in #33

**Comment by eborisch** [comment]
Aha. Thanks for the pointer!!

**Comment by eborisch** [comment]
Actually, I'll leave this open, to be closed once #33 is merged.

**Comment by vermaden** [comment]
Merged. Now all new BE's are noauto.
