### ISSUE TITLE
Implement "beadm create -d"

### ISSUE THREAD

**Issue by xen0l** [vermaden/beadm#38]
From illumos beadm manpage:

<pre>
   -d description

               Create a new BE with a description associated with it.
</pre>

This adds description to BE and that description is displayed in the boot loader screen selection menu. This can be handy for end users.

**Comment by vermaden** [comment]
FreeBSD's bootloader displays only BE name, no place for description.

**Comment by xen0l** [comment]
@vermaden you can store those in ZFS atrtibutes and make it available for beadm list output just as in Solaris world.
