### ISSUE TITLE
Implement "beadm activate -t/-T"

### ISSUE THREAD

**Issue by xen0l** [vermaden/beadm#41]
Funcionality similar to https://www.illumos.org/issues/7537 should be implemented. 

The primary use case is for developers, who develop FreeBSD and create something that can panic. Using nextboot BE, might help them.

From illumos beadm man page:
<pre>
            -t

               Sets temporary, one time activation. For next boot, the beName
               is used for boot, and the temporary activation is removed.
               When temporary activation is removed, the next boot will use
               zfs dataset specified in boot pool bootfs property.

           -T

               Removes temporary next boot configuration and makes beName the
               active BE on next boot.
</pre>

**Comment by vermaden** [comment]
Quoting from the link You provided:
> The boot loader will read the pad2 content, and will remove the
> config by zeroing the pad2 area, so the next boot will not see
> the nextboot config and will use normal bootfs property based setup.

So its not about 'beadm' util but about boot loader changes which are out of scope for this 'beadm' utility repository.

Regards,
vermaden
