### ISSUE TITLE
PATH needs restriction in beadm

### ISSUE THREAD

**Issue by nelsonbeebe** [vermaden/beadm#44]
On an up-to-date TrueOS system with
    %  beadm --version
    beadm 1.2.6 2015/09/17
I got this error:
    % /usr/local/sbin/beadm list
    awk: cmd. line:18: warning: escape sequence `\/' treated as plain `/'
    awk: cmd. line:51: fatal: attempt to use scalar `FSNAMES' as an array
If I reset the PATH and retry, I get expected output:
        % env PATH=/bin:/usr/bin:/usr/local/bin /usr/local/sbin/beadm list
        BE                              Active Mountpoint  Space Created
        initial                         -      -            7.7G 2016-09-08 04:47
        12.0-CURRENT-up-20160912_225329 -      -            4.3G 2016-09-12 22:48
        12.0-CURRENT-up-20161226_222208 -      -          149.3M 2016-12-26 22:21
        12.0-CURRENT-up-20170112_231255 NR     /          406.0G 2017-01-12 22:19
Which awk did the first instance use?

        % which awk
        /usr/uumath/bin/awk

        % /usr/uumath/bin/awk --version
        GNU Awk 4.1.4, API: 1.1 (GNU MPFR 3.1.4-p3, GNU MP 5.1.3)
        ...

The issue is in /usr/local/sbin/beadm: it has

        PATH=${PATH}:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin

That is dangerous for installation at remote sites: it should instead
ignore the user's PATH variable, and supply a fixed one:

        PATH=/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin
        export PATH

That way, it will get the needed TrueOS/FreeBSD version of awk, rather
than a locally-installed GNU gawk that might have also been named awk.

The export command shown above should be there too: it is missing in
the current beadm.

I haven't inspected the awk code in beadm: it can probably be tweaked
slightly to work with gawk, mawk, and nawk, without needing to do
feature-tests to figure out which one is being used.  I've written
>0.5 million lines of awk, and with rare exceptions, almost all of my
awk code works on all three implementations.

**Comment by vermaden** [comment]
Dunno for what reason people behind TrueOS/PC-BSD would prefer GNU awk in front of BSD awk, but this 'issue' is fixed in latest 1.2.7 version of BEADM:

https://github.com/vermaden/beadm/tree/1.2.7

Regards,
vermaden

**Comment by nelsonbeebe** [comment]
Thanks for the quick fix to beadm!  I've let Kris Moore in the TrueOS
project know about it, so the new version should soon be propagated
to that O/S.

-------------------------------------------------------------------------------
- Nelson H. F. Beebe                    Tel: +1 801 581 5254                  -
- University of Utah                    FAX: +1 801 581 4148                  -
- Department of Mathematics, 110 LCB    Internet e-mail: beebe@math.utah.edu  -
- 155 S 1400 E RM 233                       beebe@acm.org  beebe@computer.org -
- Salt Lake City, UT 84112-0090, USA    URL: http://www.math.utah.edu/~beebe/ -
-------------------------------------------------------------------------------

**Comment by vermaden** [comment]
From what I remember Kris maintains his own version of beadm suited more for PC-BSD/TrueOS so its probably already fixed there ;)Od: "nelsonbeebe" &lt;notifications@github.com&gt;Do: "vermaden/beadm" &lt;beadm@noreply.github.com&gt;; Wysłane: 19:14 Poniedziałek 2017-01-16Temat: Re: [vermaden/beadm] PATH needs restriction in beadm (#44)Thanks for the quick fix to beadm!  I've let Kris Moore in the TrueOS
project know about it, so the new version should soon be propagated
to that O/S.
-------------------------------------------------------------------------------
- Nelson H. F. Beebe                    Tel: +1 801 581 5254                  -
- University of Utah                    FAX: +1 801 581 4148                  -
- Department of Mathematics, 110 LCB    Internet e-mail: beebe@math.utah.edu  -
- 155 S 1400 E RM 233                       beebe@acm.org  beebe@computer.org -
- Salt Lake City, UT 84112-0090, USA    URL: http://www.math.utah.edu/~beebe/ -
