### ISSUE TITLE
reroot: active on reboot (R), next boot once (T)

### ISSUE THREAD

**Issue by grahamperrin** [vermaden/beadm#62]
Hi

From the usage example at <https://vermaden.wordpress.com/2022/03/14/zfs-boot-environments-revolutions/>, I assumed that `reroot` **_without_** prior activation would _temporarily_ `reroot` – like, `T` but not `R`.

Actual result
=============

Condensed: 

```text
root@mowa219-gjp4-8570p-freebsd:/usr/home/grahamperrin/dev/beadm # ./beadm create n253776-d5ad1713cc3-b
Created successfully
root@mowa219-gjp4-8570p-freebsd:/usr/home/grahamperrin/dev/beadm # script
Script started, output file is typescript
root@mowa219-gjp4-8570p-freebsd:/usr/home/grahamperrin/dev/beadm # ./beadm reroot n253776-d5ad1713cc3-b
Activated successfully
root@mowa219-gjp4-8570p-freebsd:/usr/home/grahamperrin/dev/beadm # 
…
% date ; uptime ; bectl list -c creation
Fri 18 Mar 2022 09:40:01 GMT
 9:40a.m.  up 3 days,  4:31, 2 users, load averages: 3.19, 1.73, 1.82
BE                    Active Mountpoint Space Created
n250511-5f73b3338ee-d -      -          4.94G 2021-11-13 15:43
n252381-75d20a5e386-b -      -          6.80G 2022-01-12 23:23
n252450-5efa7281a79-a -      -          6.49G 2022-01-14 19:27
n252483-c8f8299a230-b -      -          4.84G 2022-01-17 14:24
n252505-cc68614da82-a -      -          4.90G 2022-01-18 14:26
n252531-0ce7909cd0b-h -      -          5.71G 2022-02-06 12:24
n252997-b6724f7004c-c -      -          6.17G 2022-02-11 23:07
n253116-39a36707bd3-e -      -          5.66G 2022-02-20 07:03
n253343-9835900cb95-c -      -          1.54G 2022-02-27 14:58
n253627-25375b1415f-e -      -          462M  2022-03-12 18:20
n253776-d5ad1713cc3-a -      -          22.9M 2022-03-14 23:40
n253776-d5ad1713cc3-b NR     /          156G  2022-03-18 09:31
% 
```

The reroot alone resulted in `R`: 

`n253776-d5ad1713cc3-b NR     /          156G  2022-03-18 09:31`

As a default, `R` is not a bad thing :-) however there may be cases where `T` will be preferable. 

---

Side notes: 

* I wondered whether [script(1)](https://www.freebsd.org/cgi/man.cgi?query=script&sektion=1&manpath=FreeBSD) above would capture anything, of course it did not (because I did not explicitly `exit` before the reroot)
* the reroot feature is **very** cool.

**Comment by vermaden** [comment]
Hi,

this is the code for **`reroot`** option:

```
  (reroot) # -----------------------------------------------------------------
    # activate new BE which would also set new root filesystem using kenv(1)
    ${0} activate ${2}
    # reroot to new root with reboot(8) command
    reboot -r
    # no need to display messages here "because Kansas is going bye bye"
    ;;
```

So the first thing is done is the **`activate`** option.

I am not sure what other states `bectl(8)` shows as I only use `beadm(8)` and `beadm(8)`  only has `N` and `R` states.

Does is not work? The `reroot` option? I am not sure I properly understood that issue :)

Regards,
vermaden

**Comment by grahamperrin** [comment]
Sorry, I forgot that `-t` and `-T` flags are a feature of [bectl(8)](https://www.freebsd.org/cgi/man.cgi?query=bectl&sektion=8&manpath=FreeBSD). So, this issue is not valid, I'll close it. 

----

Things do work as expected. 

If I understand correctly, this step (in your blog post) is superfluous: 

`# beadm activate 13.1.safe`

**Comment by vermaden** [comment]
> Sorry, I forgot that `-t` and `-T` flags are a feature of [bectl(8)](https://www.freebsd.org/cgi/man.cgi?query=bectl&sektion=8&manpath=FreeBSD). So, this issue is not valid, I'll close it.
> 
> Things do work as expected.

OK :)

> If I understand correctly, this step (in your blog post) is superfluous:
> 
> `# beadm activate 13.1.safe`

It will not hurt but `reroot` option will also do it :)
